[package]
name = "quotient"
version = "0.2.0"
authors = ["Tom Crossland <tom.crossland@bluetab.net>"]

[dependencies]
uuid = { version = "0.8", features = ["v4"] }
byteorder = "1.3"
log = "0.4"
log4rs = "0.13"
